CREATE DATABASE cars;
GRANT ALL PRIVILEGES ON DATABASE cars TO dev;

CREATE DATABASE rental;
GRANT ALL PRIVILEGES ON DATABASE rental TO dev;

CREATE DATABASE payments;
GRANT ALL PRIVILEGES ON DATABASE payments TO dev;
