version: "3.9"

services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    pull_policy: if_not_present
    restart: always
    ports:
      - "${PG_HOST_PORT}:${PG_CONTAINER_PORT}"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ../postgres/:/docker-entrypoint-initdb.d/

volumes:
  pg-data:
